# -*- coding: utf-8 -*-
"""CIFAR-10 Image Classification (CV).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15OIbSTLHahSANsObvF06XqFWpbBGLXOs

# Project 7: CIFAR-10 Image Classification

The Goal: Classify images into 10 different real-world categories: Airplanes, Cars, Birds, Cats, Deer, Dogs, Frogs, Horses, Ships, and Trucks.

Traditional Neural Networks (like Project 6) treat images as a flat list of pixels, losing the "spatial" relationship (how pixels next to each other form lines and shapes). CNNs are designed to "see" like a human, scanning the image for features.

Pre-Development Strategy

The Architecture: We will use Convolutional Layers (to find patterns) and Pooling Layers (to shrink the image and focus on the most important parts)

The Challenge: These are color images ($32 \times 32$ pixels with 3 color channels: Red, Green, Blue). This is significantly harder than the black-and-white digits of Project 6.

The Strategy: We use "Filters" that slide across the image to detect edges, then shapes, and finally objects.
"""

"""
AI Engineering Portfolio - Project 07
Title: Real-world Image Classification (CNN)
Author: Adeel Ahmed
Strategy: Using Convolutional Neural Networks (CNN) for color image recognition.
"""

import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt

# DATA ACQUISITION
(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()

# PREPROCESSING
# Normalize pixel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0

# CNN ARCHITECTURE
model = models.Sequential([
    # First Convolutional Block
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)),
    layers.MaxPooling2D((2, 2)),

    # Second Convolutional Block
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    # Third Convolutional Block
    layers.Conv2D(64, (3, 3), activation='relu'),

    # Transition to Dense Layers
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10) # 10 output classes
])

# COMPILATION
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

# --- STEP 5: TRAINING ---
print("Training the CNN ")
history = model.fit(train_images, train_labels, epochs=10,
                    validation_data=(test_images, test_labels))

# EVALUATION
plt.plot(history.history['accuracy'], label='accuracy')
plt.plot(history.history['val_accuracy'], label = 'val_accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.ylim([0, 1])
plt.legend(loc='lower right')
plt.show()

"""explain how a CNN differs from a basic Neural Network:

Filters/Kernels: These are the small windows that slide over the image to detect features like vertical lines or curves.

Pooling (Max Pooling): This reduces the size of the data. It picks the brightest pixel in a area (e.g., $2 \times 2$) and throws away the rest, which makes the model faster and helps it ignore "noise.

"Spatial Invariance: A CNN can recognize a "cat" whether the cat is in the top-left corner or the bottom-right. A standard Neural Network often struggles with this.
"""

