# -*- coding: utf-8 -*-
"""Handwritten Digit Recognition (MNIST).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wq4g9nL2lRZBmUTS3ebGZPBq9sBA5xZC
"""



"""# Project 6: Handwritten Digit Recognition (MNIST)

The Goal: Build a model that can look at an image of a handwritten number (0-9) and correctly identify which digit it is

The Library: We will use TensorFlow and Keras.

The Architecture: A Multilayer Perceptron (MLP). This involves an Input layer (the image pixels), Hidden layers (where the "learning" happens), and an Output layer (10 neurons representing digits 0-9).

The Activation Function: We use ReLU for hidden layers to prevent the model from "dying" during training and Softmax for the output to get a probability (e.g., "90% sure this is a 5").
"""

"""
AI Engineering Portfolio - Project 06
Title: Handwritten Digit Classification
Author: Adeel Ahmed
Strategy: Building a Deep Neural Network using TensorFlow/Keras.
"""

import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

# DATA ACQUISITION
# The MNIST dataset contains 60,000 training images of digits 0-9
mnist = tf.keras.datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# PREPROCESSING
# Normalize pixel values (0-255) to be between 0 and 1.
# Neural networks perform much better with small, scaled numbers.
X_train, X_test = X_train / 255.0, X_test / 255.0

# MODEL ARCHITECTURE
model = models.Sequential([
    layers.Flatten(input_shape=(28, 28)),    # Flattens the 2D image into a 1D array
    layers.Dense(128, activation='relu'),    # Hidden layer with 128 neurons
    layers.Dropout(0.2),                     # Prevents overfitting by turning off 20% of neurons
    layers.Dense(10, activation='softmax')   # Output layer (10 digits)
])

# COMPILATION
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# TRAINING
print("Training the Neural Network...")
history = model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

# EVALUATION
test_loss, test_acc = model.evaluate(X_test,  y_test, verbose=2)
print(f'\n Test Accuracy: {test_acc:.4f}')

# Plotting Accuracy Trend
plt.plot(history.history['accuracy'], label='Accuracy')
plt.plot(history.history['val_accuracy'], label = 'Val_Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend(loc='lower right')
plt.show()

"""Epochs: One "Epoch" means the model has seen the entire training dataset once. We usually run 5-10 epochs so the model can refine its weights.

Dropout: This is a "Regularization" technique. By randomly ignoring some neurons, we force the others to work harder, which prevents the model from just memorizing the training images (Overfitting).

Softmax: This converts the output into 10 probabilities that add up to 100%. If the neuron for "5" has the highest probability, that is the model's prediction.
"""

