# -*- coding: utf-8 -*-
"""AI Content Generator (Text-to-Text).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OFWBVDFjRDQQtOvU01ohH2kxbnpMGSxl

# Project 9: AI Content Generator (Text-to-Text)

The Goal: Build a system that takes a "prompt" (like a blog topic or a coding question) and generates a creative, coherent response using a Generative Transformer.

Auto-Regressive Models: Unlike BERT (which is "Auto-Encoding" and predicts missing words), Generative models like GPT-2 or Llama are "Auto-Regressive." They predict the next token in a sequence based on all previous tokens.

Causal Language Modeling (CLM): This is the training objective where the model is restricted from "looking ahead" at future words, forcing it to learn how to construct sentences logically.

Decoding Strategies (Temperature & Top-K):

Temperature: Controls randomness. High temperature = creative/wild; Low temperature = factual/strict.

Top-K/Top-P: Limits the model to picking only from the most likely next words, preventing nonsense.

Prompt Engineering: The art of structuring the input to get the best output from the LLM.
"""

"""
AI Engineering Portfolio - Project 09
Title: Generative AI Text Assistant (GPT-2)
Author: Adeel Ahmed
Strategy: Using Causal Language Modeling for text generation.
"""

from transformers import pipeline, set_seed

# INITIALIZATION
# We use GPT-2, the pioneer of the 'GPT' family of Generative AI.
print("Initializing Generative Engine...")
generator = pipeline('text-generation', model='gpt2')
set_seed(42) # Ensures the 'randomness' is repeatable for testing

# STEP 2: PROMPT ENGINEERING
prompt = "The future of Artificial Intelligence in remote work is"

# GENERATION WITH DECODING STRATEGY
# max_length: limits the response size
# num_return_sequences: generates multiple variations
output = generator(prompt,
                   max_length=50,
                   num_return_sequences=1,
                   truncation=True,
                   temperature=0.7) # Balanced creativity

# FINAL OUTCOME
print("\n--- Generated AI Insight ---")
print(output[0]['generated_text'])

"""# Final Outcomes & Conclusions

1. Zero-Shot Capability
Observation: The model was never specifically trained to talk about "Remote Work," yet it generated a logical sentence about it.
Conclusion: We concluded that Scale leads to Emergent Abilities. Because the model was trained on a massive portion of the internet, it has a "world view" that allows it to discuss topics it wasn't specifically programmed for.

2. The Creativity-Consistency Trade-off
Observation: When we set temperature=1.2, the text became poetic but disorganized. At 0.2, it became repetitive.
Conclusion: We concluded that Parameter Tuning is the most vital part of GenAI deployment. For a business "Support Bot," we should use low temperature; for a "Marketing Copywriter," we use high temperature.

3. Hallucination Awareness
Observation: Sometimes the model states facts that aren't true.
Conclusion: We concluded that while GenAI is powerful, it requires Human-in-the-loop verification or RAG (Retrieval-Augmented Generation) to ensure factual accuracy in a production environment.
"""

