# -*- coding: utf-8 -*-
"""Real-Time Object Detection (YOLO).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xXu4fEDteEu5efR32Yc_sVhBqAfOHzKd

# Project 10: Real-Time Object Detection (YOLO)

The Goal: Build a system that can look at an image or video and not just say "there is a car," but draw a box around it and identify exactly where it is.

## Important Terminologies

YOLO (You Only Look Once): Unlike older models that look at an image thousands of times (R-CNN), YOLO passes the image through the neural network once. This is why it is fast enough for self-driving cars and real-time security cameras.

Bounding Boxes: These are the $(x, y)$ coordinates that define the rectangle around an object.

Non-Max Suppression (NMS): If the model thinks it sees 5 boxes on one dog, NMS "cleans" the results and keeps only the box with the highest confidence score.

Intersection over Union (IoU): A metric that measures how well the predicted box overlaps with the actual object.

### We will use 'ultralytics', the most professional library for YOLO.
"""

# Commented out IPython magic to ensure Python compatibility.
"""
AI Engineering Portfolio - Project 10
Title: Real-Time Object Detection with YOLOv8
Author: Adeel Ahmed
Strategy: Implementing single-pass detection for high-speed inference.
"""

# %pip install ultralytics

# Import Libraries
from ultralytics import YOLO
import cv2
# - INITIALIZATION
# Load a pre-trained YOLOv8 'Nano' model (optimized for speed/remote deployment)
print("Loading YOLOv8 Detection Engine...")
model = YOLO('yolov8n.pt')

# INFERENCE
# We will detect objects in a standard sample image (like a street scene)
results = model('https://ultralytics.com/images/bus.jpg')

# VISUALIZATION & OUTCOME
for result in results:
    # This will show the image with boxes around people, buses, and signs
    result.show()

    # Print the "Detections" (What the AI actually found)
    print("\n--- Objects Detected ---")
    for box in result.boxes:
        class_id = int(box.cls[0])
        label = model.names[class_id]
        conf = float(box.conf[0])
        print(f"Detected: {label} | Confidence: {conf:.2f}")

"""# Final Outcomes & Conclusions

1. Real-Time Feasibility
Observation: The "Nano" (yolov8n) model processed the image in milliseconds.
Conclusion: We concluded that this architecture is suitable for Edge Computing (like drones or mobile phones) because it provides high accuracy without needing a massive server.

2. Class Diversity
Observation: The model simultaneously identified humans, vehicles, and traffic lights in a single pass.
Conclusion: We concluded that YOLO’s Global Context (looking at the whole image at once) prevents "false positives" where background textures are mistaken for objects.

3. Confidence Thresholding
Observation: Objects with confidence below 0.3 were often blurry or partial.
Conclusion: We concluded that for a production-level security or safety system, a Confidence Threshold of 0.5 is the "Golden Standard" to balance safety with detection speed.
"""

