# -*- coding: utf-8 -*-
"""Deploying a "Vision-as-a-Service" Web App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u41wTd4xn4O6pPrG70jwJBu6mIwikNWl

# Project 11: Deploying a "Vision-as-a-Service" Web App

The Goal: Take your YOLO Object Detection (Project 10) or your BERT Sentiment Analysis (Project 8) and wrap it in a web interface using Streamlit. This allows anyone in the world to upload an image or text and get an AI result instantly in their browser.

## Important Terminologies

Frontend vs. Backend: The Frontend is the buttons and sliders the user sees; the Backend is your Python AI model processing the data.

Streamlit: A specialized framework for Data Scientists to build web apps in pure Python without needing to learn HTML/CSS.

Inference Pipeline: The sequence of events where a user uploads a file, the model processes it, and the results are rendered on the screen.

Edge vs. Cloud Deployment: Discussing whether the model runs on the user's device or a central server.

# Installation (Step-by-Step)
Open your terminal (CMD or PowerShell) and run these two commands. This sets up the "engine" for your website.

Install the Web Framework:
'pip install streamlit'

Install the Vision Engine:
'pip install ultralytics'

# Writing the Code
"""

# Commented out IPython magic to ensure Python compatibility.
"""
AI Engineering Portfolio - Project 11
Title: Vision-as-a-Service Web Application
Author: Adeel Ahmed
Strategy: Deploying a YOLOv8 model via a Streamlit interface.
"""
# %pip install Streamlit
# %pip install ultralytics

#import libraries
import streamlit as st
from ultralytics import YOLO
from PIL import Image
import numpy as np

# UI CONFIGURATION
st.set_page_config(page_title="AI Object Detector", layout="centered")
st.title("👁️ Real-Time Object Detection")
st.write("Upload an image and let the AI identify objects instantly.")

# MODEL LOADING
@st.cache_resource # This ensures the model only loads ONCE (Efficiency)
def load_model():
    return YOLO('yolov8n.pt')

model = load_model()

# Create the 'Upload' Button
uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

# Run the AI Detection when the user clicks this button
if st.button('🚀 Start AI Analysis'):
  with st.spinner('AI is thinking...'):
    # The AI processes the image
    results = model(original_image)

    # The AI draws boxes around the objects it found
    result_image = results[0].plot()

    # Display the final "Result" image
    st.image(result_image, caption='AI Detection Result', use_container_width=True)
    st.success("Analysis Complete!")

"""# Launching the Project (The "Streamlit" Way)

Open your terminal in the folder where app.py is saved.

Type this command and press Enter:
'python -m streamlit run app.py'
"""

