# -*- coding: utf-8 -*-
"""Spam_detection_by_NB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hy9tFe0yHhtrNgO8IM1mTsiCVtXyuANr

# An NLP-based SMS/Email spam detection system using Python, Scikit-Learn (Naive Bayes), and TF-IDF vectorization.

## Step 1: Import Libraries and Load Data
"""

import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Download necessary NLTK data
nltk.download('stopwords')
nltk.download('punkt')

# 1. Load Dataset
url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"
df = pd.read_csv(url, sep='\t', names=['label', 'message'])

print(f"Dataset Shape: {df.shape}")
print(df.head())

"""## Step 2: Data Preprocessing
We need to clean the "noise" (punctuation, capitals, and common words like "the").
"""

df.info()

df.head()

nltk.download('punkt_tab')
stemmer = PorterStemmer()
stop_words = set(stopwords.words('english'))

def clean_text(text):
    # a. Remove non-alphabetic characters and lowercase
    text = re.sub('[^a-zA-Z]', ' ', text).lower()

    # b. Tokenize (split into words)
    words = nltk.word_tokenize(text)

    # c. Remove stopwords and Stem (running -> run)
    cleaned_words = [stemmer.stem(w) for w in words if w not in stop_words]

    return ' '.join(cleaned_words)

# Apply cleaning to the entire message column
df['cleaned_message'] = df['message'].apply(clean_text)
print("\nCleaned Text Sample:")
print(df[['message', 'cleaned_message']].head())

df.info()

df.describe()

df.head()

"""## Step 3: Vectorization (Math conversion)
This turns your words into a $matrix$ of numbers using TF-IDF (Term Frequency-Inverse Document Frequency).
"""

# Initialize TF-IDF Vectorizer
tfidf = TfidfVectorizer(max_features=3000) # Only keep top 3000 most frequent words

# Convert text to numbers
X = tfidf.fit_transform(df['cleaned_message']).toarray()

# Convert labels to numbers (ham=0, spam=1)
y = pd.get_dummies(df['label'])
y = y['spam'].values # Keep only the 'spam' column

"""## Step 4: Train-Test Split
We hide 20% of the data from the AI to test it later.
"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training set size: {len(X_train)}")
print(f"Testing set size: {len(X_test)}")

"""## Step 5: Build and Train the Model
We use Multinomial Naive Bayes. It’s mathematically perfect for word counts.
"""

# Initialize the model
model = MultinomialNB()

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

"""## Step 6: Evaluation"""

print("\n--- Model Performance ---")
print(f"Accuracy Score: {accuracy_score(y_test, y_pred) * 100:.2f}%")
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nDetailed Report:")
print(classification_report(y_test, y_pred))

"""## Step 7: Create a Real-World Tester
test any custom message.
"""

def predict_spam(sample_message):
    processed = clean_text(sample_message)
    vectorized = tfidf.transform([processed]).toarray()
    prediction = model.predict(vectorized)

    if prediction[0] == 1:
        return "SPAM"
    else:
        return "HAM (Normal)"

# Test it!
print("\nTesting Custom Messages:")
print(f"Message 1: 'Win a free iPhone now!' -> {predict_spam('Win a free iPhone now!')}")
print(f"Message 2: 'Hey, are we still meeting for lunch?' -> {predict_spam('Hey, are we still meeting for lunch?')}")