# -*- coding: utf-8 -*-
"""Customer Segmentation (K-Means Clustering).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LjbTkXqChVSdvhPGxJ2seh9r5qoAjf_d

# Project 3: Customer Segmentation (K-Means Clustering)

Business Goal: Partition mall customers into distinct groups based on income and spending habits to enable targeted marketing strategies.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler

# --- DATA ACQUISITION (STABLE & VERIFIED) ---
url = "https://raw.githubusercontent.com/SteffiPeTaffy/machineLearningAZ/master/Machine%20Learning%20A-Z%20Template%20Folder/Part%204%20-%20Clustering/Section%2025%20-%20Hierarchical%20Clustering/Mall_Customers.csv"

# Verify data retrieval
df = pd.read_csv(url)
print("🚀 Data successfully retrieved! Rows:", df.shape[0])
print(df.head())

# --- PREPROCESSING ---
# Select 'Annual Income (k$)' and 'Spending Score (1-100)'
X = df.iloc[:, [3, 4]].values

# Strategy: StandardScaler is essential for K-Means (Euclidean distance)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# --- THE ELBOW METHOD ---
wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

plt.figure(figsize=(8, 4))
plt.plot(range(1, 11), wcss, marker='o', color='navy')
plt.title('Elbow Method for Optimal K')
plt.show()

# --- TRAINING & EVALUATION ---
# Optimal K from the elbow is 5
kmeans = KMeans(n_clusters=5, init='k-means++', random_state=42)
y_kmeans = kmeans.fit_predict(X_scaled)

score = silhouette_score(X_scaled, y_kmeans)
print(f"📊 Silhouette Score: {score:.3f} (Values > 0.5 indicate strong clustering)")

# --- VISUALIZATION ---
plt.figure(figsize=(10, 6))
sns.scatterplot(x=X[:, 0], y=X[:, 1], hue=y_kmeans, palette='bright', s=100, edgecolor='black')
plt.scatter(kmeans.cluster_centers_[:, 0] * scaler.scale_[0] + scaler.mean_[0],
            kmeans.cluster_centers_[:, 1] * scaler.scale_[1] + scaler.mean_[1],
            s=200, c='black', marker='X', label='Centroids')
plt.title('Customer Segments')
plt.legend(title='Clusters')
plt.show()