# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pkyimJFn4YwVcuJ7Ach51ZW3h_eruJHF
"""



"""# Project 03: Telco Customer Churn Predictor

While spam filter was a binary "Yes/No," churn prediction often requires to output a probability score. This is perfect for practicing how to tune your Precision-Recall threshold based on business needs. This project is a step up because it requires Handling Class Imbalance and Feature Engineering.

The Problem: Customer Churn (losing customers) is expensive.

The Data: 7,000+ customers with 21 features (Tenure, Monthly Charges, Contract type, etc.).

The Challenge: The data is "imbalanced" (most people stay, few leave). If the AI ignores the people who leave, it's useless.

The Strategy: Use Random Forest and Logistic Regression, then handle categorical data using One-Hot Encoding.
"""

"""
AI Engineering Portfolio - Project 04
Title: Telco Customer Churn Prediction
Author: Adeel Ahmed
Strategy: Predicting customer exit (Churn) using Supervised Classification.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Data Acquisition
import pandas as pd
import numpy as np

# Direct URL to the dataset
url = "https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv"
df = pd.read_csv(url)

# Preview the data
print(df.info())
df.head()

# DATA CLEANING
# TotalCharges is often read as text but should be numeric.
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
# remove null values
df.dropna(inplace=True)

df.info()

# Drop ID (irrelevent)
df.drop('customerID', axis=1, inplace=True)

# FEATURE ENGINEERING
# Convert categorical text (Yes/No) into numbers.
le = LabelEncoder()
for col in df.select_dtypes(include=['object']).columns:
    df[col] = le.fit_transform(df[col])

df.head()

# TRAIN-TEST SPLIT
X = df.drop('Churn', axis=1)
y = df['Churn']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# MODEL TRAINING
# Using Random Forest to handle non-linear relationships in customer behavior.
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# EVALUATION
y_pred = model.predict(X_test)
print("Model Performance")
print(classification_report(y_test, y_pred))

# Visualization of the Confusion Matrix
plt.figure(figsize=(6,4))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix: Churn vs No Churn')
plt.show()

# Business Insight - What drives Churn?
importances = model.feature_importances_
feat_importances = pd.Series(importances, index=X.columns)
feat_importances.nlargest(10).plot(kind='barh')
plt.title('Top 10 Drivers of Customer Churn')
plt.show()

"""Imbalanced Data: In churn, the "Churn=Yes" group is much smaller than "Churn=No." If you only look at Accuracy, you might be fooled. You must look at F1-Score and Recall.

Recall (Sensitivity): This is the most important metric here. It measures: "Out of all people who actually left, how many did we catch?"           One-Hot Encoding vs. Label Encoding: We used Label Encoding (0, 1, 2). "For Tree-based models like Random Forest, Label Encoding is efficient and doesn't explode the feature space."
"""

