# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SZKyck0f9QoRVK7rC5kk51CIIcOBfT7Z

# Project 2: California House Price Predictor (Random Forest Regressor)
"""

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# Data ACQUISITION
data = fetch_california_housing()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['Target_Price'] = data.target

df.head()

df.info()

# EXPLORATORY DATA ANALYSIS (EDA) - Strategy: Identifying Multi-collinearity
# look for features that are too similar to avoid "overfitting."
plt.figure(figsize=(12, 8))
sns.heatmap(df.corr(), annot=True, cmap='RdYlGn')
plt.title("Correlation Matrix: Finding the strongest drivers of Price")
plt.show()

# Strategy: Detecting and Filtering Outliers using the IQR Method
def detect_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Identify outliers
    outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]
    print(f"Detected {len(outliers)} outliers in '{column}'")
    return lower_bound, upper_bound

# Let's check 'MedInc' (Median Income) as it's the most important feature
lower, upper = detect_outliers(df, 'MedInc')

# Strategy: Visualization for the Business Team
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 4))
sns.boxplot(x=df['MedInc'])
plt.title("Boxplot for Outlier Detection in Median Income")
plt.show()

# DATA CLEANING & PREPROCESSING
# Strategy: Feature Scaling. Regression models are sensitive to the "scale" of numbers.
X = df.drop('Target_Price', axis=1)
y = df['Target_Price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# MODEL SELECTION - Strategy: Ensemble Methods
# Why Random Forest? It handles non-linear relationships better than Simple Linear Regression.
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train_scaled, y_train)

# Strategy: Extracting and Visualizing Feature Importance from Random Forest
# Note: 'model' is your trained RandomForestRegressor from the previous step

importances = model.feature_importances_
feature_names = data.feature_names
feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances})

# Sort by importance
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

# Strategy: Visual Presentation (Essential for remote meetings/reports)
plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=feature_importance_df, palette='viridis')
plt.title("Feature Importance: Which factors drive house prices?")
plt.xlabel("Importance Score (0.0 to 1.0)")
plt.show()

print("\nFeature Importance Rankings:")
print(feature_importance_df)

# PREDICTION & EVALUATION
y_pred = model.predict(X_test_scaled)

# Strategy: Business-Centric Metrics
# Managers care about "How much money are we off by?"
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"--- Project 2 Results ---")
print(f"Mean Absolute Error: ${mae * 100000:.2f}") # Prices are in units of $100k
print(f"R-Squared (Accuracy): {r2 * 100:.2f}%")

import joblib
joblib.dump(model, 'house_price_model.pkl')

"""Key Terminology for Project 2:
StandardScaler: Adjusts all numbers (Income, Age, Population) to be on the same scale (0 to 1 or -3 to 3) so the model doesn't give more weight to "Population" just because its numbers are bigger.

Random Forest: A "Forest" of Decision Trees that vote on the final price to reduce errors.

Mean Absolute Error (MAE): The average amount the model is "off." If MAE is 0.5, and prices are in 100k dollars units, your model is off by $50,000 on average.
"""

