# -*- coding: utf-8 -*-
"""Gold Price Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZmYt2n0wSJ9rJyfBxO1wYU2MQgtUHKlY
"""



"""# Project 5: Gold Price Forecasting

We’ll use a library called Prophet (developed by Meta/Facebook), which is the industry standard for handling "Seasonality" (trends that repeat daily, weekly, or yearly).

never use train_test_split with shuffle=True for time data. You must train on the "Past" and test on the "Future."

AI Engineering Portfolio - Project 05
Title: Gold Price Forecasting using Prophet
Strategy: Time-series analysis to predict future commodity prices.
"
"""

!pip install prophet

import pandas as pd
from prophet import Prophet
import matplotlib.pyplot as plt

# DATA ACQUISITION
url = "https://raw.githubusercontent.com/amankharwal/Website-data/master/gold_price.csv"
df = pd.read_csv(url)
df.info()

df.head()

# PREPROCESSING
df['Date'] = pd.to_datetime(df['Date'])

print(df.columns)

"""Prophet requires a very simple two-column format. We need to ignore the GBP and EURO columns and extract only what we need."""

# Select only the Date and USD Morning Price
df_prophet = df[['Date', 'USD (AM)']].copy()

# the target column to be named 'y'
df_prophet = df_prophet.rename(columns={'USD (AM)': 'y','Date': 'ds'})

#Financial data often has missing values (NaN) on holidays.
# We must drop them or the model will fail.
df_prophet = df_prophet.dropna()

df_prophet.info()

""""Why only use 'USD (AM)'?"

Redundancy: "The PM price is highly correlated with the AM price; using both for a simple trend forecast adds redundancy without adding much new signal."

Standardization: "USD (AM) is a globally recognized benchmark for gold pricing, making the model's output more relevant for standard financial reporting."
"""

# Train the model
model = Prophet(yearly_seasonality=True, daily_seasonality=False)
model.fit(df_prophet)

# FORECASTING
future = model.make_future_dataframe(periods=365)
forecast = model.predict(future)

# VISUALIZATION
fig1 = model.plot(forecast)
plt.title("Gold Price Forecast: Next 1 Year")
plt.show()

