# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nsVXGKhBgxmeco7CObv19QgkMWv8Z6-V
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit ultralytics
import streamlit as st
from ultralytics import YOLO
from PIL import Image
import numpy as np

# 1. Setup the Webpage Title
st.set_page_config(page_title="AI Vision App")
st.title("👁️ Real-Time Object Detection")
st.write("Upload any photo, and my AI model will find the objects inside it!")

# 2. Load the AI Model (YOLOv8)
# We use 'cache_resource' so the model stays in memory and doesn't slow down.
@st.cache_resource
def get_model():
    return YOLO('yolov8n.pt')

model = get_model()

# 3. Create the 'Upload' Button
uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

# --- THE FIX IS HERE ---
if uploaded_file is not None:
    # We define 'original_image' here
    original_image = Image.open(uploaded_file) 
    st.image(original_image, caption='Your Uploaded Image', use_container_width=True)
    
    # The button MUST be inside this 'if' block so it can see 'original_image'
    if st.button('🚀 Start AI Analysis'):
        with st.spinner('AI is thinking...'):
            # Now 'original_image' is guaranteed to exist when the button is pressed
            results = model(original_image)
            
            result_image = results[0].plot()
            st.image(result_image, caption='AI Detection Result', use_container_width=True)
            st.success("Analysis Complete!")